import {
  Angela,
  Anna,
  Jacob,
  Kimberly,
  Mark,
  Nathan,
  Rizky,
  Chess,
} from "./assets";

export const data = [
  {
    img: Mark,
    name: "Mark Webber",
    action: "reacted to your post",
    post: "My first tournament today!",
    group: "",
    isNew: true,
    time: "1m",
    msg: "",
    photo: "",
  },
  {
    img: Angela,
    name: "Angela Gray",
    action: "followed you",
    post: "",
    group: "",
    isNew: true,
    time: "5m",
    msg: "",
    photo: "",
  },
  {
    img: Jacob,
    name: "Jacob Thompson",
    action: "has joined your group",
    post: "",
    group: "Chess Club",
    isNew: true,
    time: "1 day",
    msg: "",
    photo: "",
  },
  {
    img: Rizky,
    name: "Rizky Hasanuddin",
    action: "sent you a private message",
    post: "",
    group: "",
    isNew: false,
    time: "5 days",
    msg: "Hello, thanks for setting up the Chess Club. I've been a member for a few weeks now and I'm already having lots of fun and improving my game.",
    photo: "",
  },
  {
    img: Kimberly,
    name: "Kimberly Smith",
    action: "commented on your picture",
    post: "",
    group: "",
    isNew: false,
    time: "1 week",
    msg: "",
    photo: Chess,
  },
  {
    img: Nathan,
    name: "Nathan Peterson",
    action: "reacted to your recent post",
    post: "5 end-game strategies to increase your win rate",
    group: "",
    isNew: false,
    time: "2 weeks",
    msg: "",
    photo: "",
  },
  {
    img: Anna,
    name: "Anna Kim",
    action: "left the group",
    post: "",
    group: "Chess Club",
    isNew: false,
    time: "2 weeks",
    msg: "",
    photo: "",
  },
];
